version: '3.8'

services:
  bot:
    build: .
    container_name: video_encoder_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - bot_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  mongodb_data:
